import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const html = readFileSync(new URL("../../index.html", import.meta.url), "utf8");
const script = readFileSync(new URL("../../app.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../../styles.css", import.meta.url), "utf8");

test("static demo exposes the current release and ship-packet surface", () => {
  assert.match(html, /F435/);
  assert.match(html, /data-panel="packet"/);
  assert.match(html, /id="packetPanel"/);
  assert.match(html, /Ship packet/);
  assert.match(html, /aria-label="Operations views"/);
  assert.match(html, /data-evidence-filter="passed"/);
  assert.match(html, /data-evidence-status="action"/);
  assert.match(html, /data-demo="Launch monitoring"/);
  assert.match(html, /15m/);
  assert.match(html, /7d/);
  assert.match(html, /data-panel="launch"/);
  assert.match(html, /id="launchPanel"/);
  assert.match(html, /Decision: hold publication/);
  assert.match(html, /data-panel="decision"/);
  assert.match(html, /id="decisionPanel"/);
  assert.match(html, /Publication decision: hold/);
  assert.match(html, /data-panel="publish"/);
  assert.match(html, /id="publishPanel"/);
  assert.match(html, /Publish command: disabled/);
  assert.match(html, /data-panel="staging"/);
  assert.match(html, /id="stagingPanel"/);
  assert.match(html, /Staging promotion: blocked/);
  assert.match(html, /data-panel="production"/);
  assert.match(html, /id="productionPanel"/);
  assert.match(html, /Production cutover: blocked/);
  assert.match(html, /data-panel="exception"/);
  assert.match(html, /id="exceptionPanel"/);
  assert.match(html, /Launch exception: denied/);
  assert.match(html, /data-panel="closeout"/);
  assert.match(html, /id="closeoutPanel"/);
  assert.match(html, /Closeout decision: blocked/);
  assert.match(html, /data-panel="archive"/);
  assert.match(html, /id="archivePanel"/);
  assert.match(html, /Archive package: blocked/);
  assert.match(html, /data-panel="remediation"/);
  assert.match(html, /id="remediationPanel"/);
  assert.match(html, /Remediation closure: blocked/);
  assert.match(html, /data-panel="governance"/);
  assert.match(html, /id="governancePanel"/);
  assert.match(html, /Governance decision: blocked/);
  assert.match(html, /data-panel="council"/);
  assert.match(html, /id="councilPanel"/);
  assert.match(html, /Council outcome: blocked/);
  assert.match(html, /data-panel="executive"/);
  assert.match(html, /id="executivePanel"/);
  assert.match(html, /Executive signoff: blocked/);
  assert.match(html, /data-panel="publication"/);
  assert.match(html, /id="publicationPanel"/);
  assert.match(html, /Publication authorization: blocked/);
  assert.match(html, /data-panel="finalization"/);
  assert.match(html, /id="finalizationPanel"/);
  assert.match(html, /Production finalization: blocked/);
  assert.match(html, /data-panel="acceptance"/);
  assert.match(html, /id="acceptancePanel"/);
  assert.match(html, /Operational acceptance: blocked/);
  assert.match(html, /data-panel="certification"/);
  assert.match(html, /id="certificationPanel"/);
  assert.match(html, /Release certification: blocked/);
  assert.match(html, /data-panel="shipauth"/);
  assert.match(html, /id="shipauthPanel"/);
  assert.match(html, /Ship authorization: blocked/);
  assert.match(html, /aria-label="MGT Skin Care home"/);
  assert.match(html, /class="brand-mark-image" src="mgt-mark\.svg"/);
  assert.match(html, /<small class="build-version">v2\.13<\/small>/);
  assert.match(html, /aria-label="Operational health preview"/);
  assert.match(html, /Queue pressure, aging work and service targets/);
  assert.match(html, /DEDUPLICATED ALERT DELIVERY/);
  assert.match(html, /5 phase groups/);
  assert.match(html, /id="flows"/);
  assert.match(html, /Six controlled service paths/);
  assert.match(html, /Free \+ Premium/);
  assert.match(html, /signed billing event is reconciled/);
  assert.match(html, /No MGT product checkout/);
  assert.doesNotMatch(html, /<th scope="col">Essential<\/th>/);
  assert.doesNotMatch(html, /<th scope="col">Guided<\/th>/);
  assert.doesNotMatch(html, /<th scope="col">Studio<\/th>/);
});

test("static demo keeps the ship packet interactive and clearly sample-only", () => {
  assert.match(script, /"Ship packet"/);
  assert.match(script, /Drafted, not approved/);
  assert.match(script, /activateEvidenceFilter/);
  assert.match(script, /"Launch monitoring"/);
  assert.match(script, /Defined, not staffed/);
  assert.match(script, /"Launch plan"/);
  assert.match(script, /Hold publication/);
  assert.match(script, /"Release decision"/);
  assert.match(script, /Hold · incomplete/);
  assert.match(script, /"Publish readiness"/);
  assert.match(script, /Blocked · no publish/);
  assert.match(script, /"Staging readiness"/);
  assert.match(script, /Blocked · no staging/);
  assert.match(script, /"Production handoff"/);
  assert.match(script, /Blocked · no production/);
  assert.match(script, /"Launch exception"/);
  assert.match(script, /Denied · no exception/);
  assert.match(script, /"Post-launch review"/);
  assert.match(script, /Blocked · no closeout/);
  assert.match(script, /"Evidence archive"/);
  assert.match(script, /Blocked · no archive/);
  assert.match(script, /"Audit remediation"/);
  assert.match(script, /Blocked · no closure/);
  assert.match(script, /"Governance review"/);
  assert.match(script, /Blocked · no decision/);
  assert.match(script, /"Release council"/);
  assert.match(script, /Blocked · no outcome/);
  assert.match(script, /"Executive signoff"/);
  assert.match(script, /Blocked · no signoff/);
  assert.match(script, /"Publication authorization"/);
  assert.match(script, /Blocked · no authorization/);
  assert.match(script, /"Production finalization"/);
  assert.match(script, /Blocked · no finalization/);
  assert.match(script, /"Operational acceptance"/);
  assert.match(script, /Blocked · no acceptance/);
  assert.match(script, /"Release certification"/);
  assert.match(script, /Blocked · no certification/);
  assert.match(script, /"Ship authorization"/);
  assert.match(script, /Blocked · no ship authorization/);
  assert.match(html, /sample records only/);
  assert.match(html, /publication gate/i);
});

test("static demo has responsive ship-packet styling", () => {
  assert.match(styles, /\.packet-grid/);
  assert.match(styles, /\.brand-mark-image/);
  assert.match(styles, /\.packet-callout/);
  assert.match(styles, /packet-grid \{ grid-template-columns: 1fr; \}/);
  assert.match(styles, /\.monitoring-grid/);
  assert.match(styles, /\.operations-health-preview/);
  assert.match(styles, /\.launch-grid/);
  assert.match(styles, /\.decision-grid/);
  assert.match(styles, /\.publish-grid/);
  assert.match(styles, /\.staging-grid/);
  assert.match(styles, /\.production-grid/);
  assert.match(styles, /\.exception-grid/);
  assert.match(styles, /\.closeout-grid/);
  assert.match(styles, /\.archive-grid/);
  assert.match(styles, /\.remediation-grid/);
  assert.match(styles, /\.governance-grid/);
  assert.match(styles, /\.council-grid/);
  assert.match(styles, /\.executive-grid/);
  assert.match(styles, /\.publication-grid/);
  assert.match(styles, /\.finalization-grid/);
  assert.match(styles, /\.acceptance-grid/);
  assert.match(styles, /\.certification-grid/);
  assert.match(styles, /\.shipauth-grid/);
  assert.match(styles, /\.flow-map-grid/);
  assert.match(script, /id: "free"/);
  assert.match(script, /id: "premium"/);
  assert.doesNotMatch(script, /id: "essential"/);
  assert.doesNotMatch(script, /id: "guided"/);
  assert.doesNotMatch(script, /id: "studio"/);
});
