import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseReceiptVerificationChecksum, RELEASE_RECEIPT_VERIFICATION_RECORD_IDS } from "./release-execution-receipt-verification.mjs";
import { buildFinalReleaseVerification, finalReleaseVerificationChecksum, validateFinalReleaseVerification, verifyFinalReleaseVerification, FINAL_RELEASE_VERIFICATION_RECORD_IDS } from "./final-release-verification.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-final-release-")); fs.mkdirSync(path.join(root, "work", "final"), { recursive: true }); for (const id of FINAL_RELEASE_VERIFICATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "final", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function receipt(value, status = "pending_external_execution_intake") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, execution_intake_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_receipt_verification" ? RELEASE_RECEIPT_VERIFICATION_RECORD_IDS.map((id) => ({ id, reference: `work/verification/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], receipt_verification_checksum: "" }; result.receipt_verification_checksum = releaseReceiptVerificationChecksum(result); return result; }
function records() { return Object.fromEntries(FINAL_RELEASE_VERIFICATION_RECORD_IDS.map((id) => [id, { reference: `work/final/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until receipt verification is ready", () => { const value = manifest(); const result = buildFinalReleaseVerification({ root: rootFixture(), manifest: value, receiptVerification: receipt(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_receipt_verification"); });
test("accepts twenty final-release records", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_receipt_verification"); const result = buildFinalReleaseVerification({ root, manifest: value, receiptVerification: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_final_release_review"); assert.equal(validateFinalReleaseVerification(result, { manifest: value, receiptVerification: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.final_release_verification_checksum, finalReleaseVerificationChecksum(result)); assert.equal(verifyFinalReleaseVerification({ root, document: result }).ok, true); });
test("detects a changed final-release record", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_receipt_verification"); const result = buildFinalReleaseVerification({ root, manifest: value, receiptVerification: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "final", "monitoring_evidence.md"), "changed\n"); assert.equal(verifyFinalReleaseVerification({ root, document: result }).ok, false); });
test("rejects a fabricated final-release state", () => { const value = manifest(); const review = receipt(value); const result = buildFinalReleaseVerification({ root: rootFixture(), manifest: value, receiptVerification: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_final_release_review"; assert.equal(validateFinalReleaseVerification(result, { manifest: value, receiptVerification: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
