import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { launchObservationReviewChecksum, LAUNCH_OBSERVATION_RECORD_IDS } from "./production-launch-observation-review.mjs";
import { buildPostLaunchMonitoringReview, postLaunchMonitoringChecksum, validatePostLaunchMonitoringReview, verifyPostLaunchMonitoringReview, POST_LAUNCH_MONITORING_RECORD_IDS } from "./post-launch-monitoring-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-post-launch-")); fs.mkdirSync(path.join(root, "work", "monitoring"), { recursive: true }); for (const id of POST_LAUNCH_MONITORING_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "monitoring", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function observation(value, status = "pending_launch_execution_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, launch_execution_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_launch_observation" ? LAUNCH_OBSERVATION_RECORD_IDS.map((id) => ({ id, reference: `work/observation/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], launch_observation_review_checksum: "" }; result.launch_observation_review_checksum = launchObservationReviewChecksum(result); return result; }
function records() { return Object.fromEntries(POST_LAUNCH_MONITORING_RECORD_IDS.map((id) => [id, { reference: `work/monitoring/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until launch observation is ready", () => { const value = manifest(); const result = buildPostLaunchMonitoringReview({ root: rootFixture(), manifest: value, launchObservationReview: observation(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_launch_observation"); });
test("accepts ten post-launch monitoring records", () => { const root = rootFixture(); const value = manifest(); const review = observation(value, "ready_for_launch_observation"); const result = buildPostLaunchMonitoringReview({ root, manifest: value, launchObservationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_post_launch_review"); assert.equal(validatePostLaunchMonitoringReview(result, { manifest: value, launchObservationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.post_launch_monitoring_checksum, postLaunchMonitoringChecksum(result)); assert.equal(verifyPostLaunchMonitoringReview({ root, document: result }).ok, true); });
test("detects a changed monitoring record", () => { const root = rootFixture(); const value = manifest(); const review = observation(value, "ready_for_launch_observation"); const result = buildPostLaunchMonitoringReview({ root, manifest: value, launchObservationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "monitoring", "backup_state_review.md"), "changed\n"); assert.equal(verifyPostLaunchMonitoringReview({ root, document: result }).ok, false); });
test("rejects a fabricated post-launch state", () => { const value = manifest(); const review = observation(value); const result = buildPostLaunchMonitoringReview({ root: rootFixture(), manifest: value, launchObservationReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_post_launch_review"; assert.equal(validatePostLaunchMonitoringReview(result, { manifest: value, launchObservationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
