import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionDecisionReviewChecksum, PRODUCTION_DECISION_RECORD_IDS } from "./production-decision-review.mjs";
import { buildProductionLaunchReadiness, productionLaunchReadinessChecksum, validateProductionLaunchReadiness, verifyProductionLaunchReadiness, PRODUCTION_LAUNCH_RECORD_IDS } from "./production-launch-readiness.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-launch-")); fs.mkdirSync(path.join(root, "work", "launch"), { recursive: true }); for (const id of PRODUCTION_LAUNCH_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "launch", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function decision(value, status = "pending_final_release_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, final_release_verification_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_decision" ? PRODUCTION_DECISION_RECORD_IDS.map((id) => ({ id, reference: `work/decision/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_decision_review_checksum: "" }; result.production_decision_review_checksum = productionDecisionReviewChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_LAUNCH_RECORD_IDS.map((id) => [id, { reference: `work/launch/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until production decision is ready", () => { const value = manifest(); const result = buildProductionLaunchReadiness({ root: rootFixture(), manifest: value, productionDecisionReview: decision(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_decision"); });
test("accepts twenty launch-readiness records", () => { const root = rootFixture(); const value = manifest(); const review = decision(value, "ready_for_production_decision"); const result = buildProductionLaunchReadiness({ root, manifest: value, productionDecisionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_launch_window"); assert.equal(validateProductionLaunchReadiness(result, { manifest: value, productionDecisionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_launch_readiness_checksum, productionLaunchReadinessChecksum(result)); assert.equal(verifyProductionLaunchReadiness({ root, document: result }).ok, true); });
test("detects a changed launch-readiness record", () => { const root = rootFixture(); const value = manifest(); const review = decision(value, "ready_for_production_decision"); const result = buildProductionLaunchReadiness({ root, manifest: value, productionDecisionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "launch", "rollback_activation.md"), "changed\n"); assert.equal(verifyProductionLaunchReadiness({ root, document: result }).ok, false); });
test("rejects a fabricated launch-window state", () => { const value = manifest(); const review = decision(value); const result = buildProductionLaunchReadiness({ root: rootFixture(), manifest: value, productionDecisionReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_launch_window"; assert.equal(validateProductionLaunchReadiness(result, { manifest: value, productionDecisionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
