import test from "node:test";
import assert from "node:assert/strict";
import { buildProductionPrerequisites } from "./production-prerequisites.mjs";

const BASE = { NODE_ENV: "production", DEMO_MODE: "false", PUBLIC_ORIGIN: "https://portal.mgt-skin-care.test", DATABASE_URL: "postgresql://u:p@db.mgt-skin-care.test:5432/postgres?sslmode=verify-full", PORTAL_AUTO_MIGRATE: "false", PORTAL_DOMAIN: "portal.mgt-skin-care.test", NODE_IMAGE: "node@sha256:" + "a".repeat(64), API_IMAGE: "ghcr.io/mgt/api@sha256:" + "d".repeat(64), WEB_IMAGE: "ghcr.io/mgt/web@sha256:" + "e".repeat(64), OLLAMA_IMAGE: "ollama/ollama@sha256:" + "b".repeat(64), CADDY_IMAGE: "caddy@sha256:" + "c".repeat(64), SUPABASE_URL: "https://project.supabase.co", SUPABASE_ANON_KEY: "anon", SUPABASE_SERVICE_ROLE_KEY: "service", OLLAMA_ENABLED: "true", OLLAMA_BASE_URL: "https://ollama.mgt-skin-care.test", OPENCLAW_ENABLED: "false", WORKER_INTERVAL_SECONDS: "60", WORKER_READINESS_MAX_AGE_SECONDS: "300", BACKUP_MAX_AGE_HOURS: "26", BACKUP_RESTORE_MAX_AGE_DAYS: "90", NOTIFICATION_DELIVERY: "in_app", SUPPORT_OWNER_NAME: "Support Owner", SUPPORT_OWNER_EMAIL: "support@mgt-skin-care.test", ACCESSIBILITY_VALIDATION_REPORT_URL: "https://evidence.mgt-skin-care.test/accessibility", ACCESSIBILITY_VALIDATED_AT: "2026-01-01T00:00:00.000Z", MONITORING_DASHBOARD_URL: "https://monitoring.mgt-skin-care.test/dashboard", INCIDENT_RUNBOOK_URL: "https://operations.mgt-skin-care.test/runbook", ALERT_OWNER_EMAIL: "alerts@mgt-skin-care.test", SUPPORT_RESPONSE_TARGET_HOURS: "24", OPERATIONS_ALERT_DELIVERY: "webhook", OPERATIONS_ALERT_WEBHOOK_URL: "https://alerts.mgt-skin-care.test/events", OPERATIONS_ALERT_WEBHOOK_TOKEN: "configured-alert-token", SUBSCRIPTIONS_ENABLED: "false" };

test("reports configuration blockers without serializing values", () => { const result = buildProductionPrerequisites({ env: {}, candidateCommit: "abc" }); assert.equal(result.status, "blocked_on_configuration"); assert.equal(JSON.stringify(result).includes("DATABASE_URL"), true); assert.equal(JSON.stringify(result).includes("postgresql://"), false); });
test("keeps a valid lean profile blocked on external evidence", () => { const result = buildProductionPrerequisites({ env: BASE, candidateCommit: "0123456789abcdef0123456789abcdef01234567" }); assert.equal(result.local.configuration.status, "ready_for_live_validation"); assert.equal(result.status, "blocked_on_external_prerequisites"); assert.equal(result.external.length, 10); assert.ok(result.external.every((item) => item.status === "pending_external_evidence")); });
test("does not expose secret-like input", () => { const result = buildProductionPrerequisites({ env: { ...BASE, SUPABASE_SERVICE_ROLE_KEY: "super-secret-value" }, candidateCommit: "0123456789abcdef0123456789abcdef01234567" }); assert.equal(JSON.stringify(result).includes("super-secret-value"), false); });
test("binds the exact candidate when supplied", () => { const commit = "0123456789abcdef0123456789abcdef01234567"; assert.equal(buildProductionPrerequisites({ env: BASE, candidateCommit: commit }).candidate_commit, commit); });
