import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionReconciliationChecksum, PRODUCTION_RECONCILIATION_RECORD_IDS } from "./production-reconciliation-review.mjs";
import { buildProductionAuthorizationReview, productionAuthorizationChecksum, validateProductionAuthorizationReview, verifyProductionAuthorizationReview, PRODUCTION_AUTHORIZATION_RECORD_IDS } from "./production-authorization-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-authorization-")); fs.mkdirSync(path.join(root, "work", "authorization"), { recursive: true }); for (const id of PRODUCTION_AUTHORIZATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "authorization", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function reconciliation(value, status = "pending_production_closeout_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_closeout_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_reconciliation" ? PRODUCTION_RECONCILIATION_RECORD_IDS.map((id) => ({ id, reference: `work/reconciliation/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_reconciliation_checksum: "" }; result.production_reconciliation_checksum = productionReconciliationChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_AUTHORIZATION_RECORD_IDS.map((id) => [id, { reference: `work/authorization/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until reconciliation is ready", () => { const value = manifest(); const result = buildProductionAuthorizationReview({ root: rootFixture(), manifest: value, productionReconciliationReview: reconciliation(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_reconciliation"); });
test("accepts twenty-five authorization records", () => { const root = rootFixture(); const value = manifest(); const review = reconciliation(value, "ready_for_production_reconciliation"); const result = buildProductionAuthorizationReview({ root, manifest: value, productionReconciliationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_authorization"); assert.equal(validateProductionAuthorizationReview(result, { manifest: value, productionReconciliationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_authorization_checksum, productionAuthorizationChecksum(result)); assert.equal(verifyProductionAuthorizationReview({ root, document: result }).ok, true); });
test("detects a changed authorization record", () => { const root = rootFixture(); const value = manifest(); const review = reconciliation(value, "ready_for_production_reconciliation"); const result = buildProductionAuthorizationReview({ root, manifest: value, productionReconciliationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "authorization", "rollback_command_confirmation.md"), "changed\n"); assert.equal(verifyProductionAuthorizationReview({ root, document: result }).ok, false); });
test("rejects a fabricated authorization state", () => { const value = manifest(); const review = reconciliation(value); const result = buildProductionAuthorizationReview({ root: rootFixture(), manifest: value, productionReconciliationReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_authorization"; assert.equal(validateProductionAuthorizationReview(result, { manifest: value, productionReconciliationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
