import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionFinalCloseoutReview, productionFinalCloseoutChecksum, validateProductionFinalCloseoutReview, verifyProductionFinalCloseoutReview, PRODUCTION_FINAL_CLOSEOUT_RECORD_IDS } from "./production-final-closeout-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-final-closeout-")); fs.mkdirSync(path.join(root, "work", "closeout-final"), { recursive: true }); for (const id of PRODUCTION_FINAL_CLOSEOUT_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "closeout-final", `${id}.md`), `${id} record\n`); return root; }
function postLaunch(status = "pending_launch_readiness") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", production_post_launch_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_FINAL_CLOSEOUT_RECORD_IDS.map((id) => [id, { reference: `work/closeout-final/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until post-launch review is ready", () => { const result = buildProductionFinalCloseoutReview({ root: rootFixture(), postLaunchReview: postLaunch(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_post_launch_review"); assert.equal(PRODUCTION_FINAL_CLOSEOUT_RECORD_IDS.length, 30); });
test("accepts thirty closeout records", () => { const root = rootFixture(); const upstream = postLaunch("ready_for_post_launch_review"); const result = buildProductionFinalCloseoutReview({ root, postLaunchReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_closeout"); assert.equal(validateProductionFinalCloseoutReview(result, { postLaunchReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_final_closeout_checksum, productionFinalCloseoutChecksum(result)); assert.equal(verifyProductionFinalCloseoutReview({ root, document: result }).ok, true); });
test("detects a changed closeout record", () => { const root = rootFixture(); const upstream = postLaunch("ready_for_post_launch_review"); const result = buildProductionFinalCloseoutReview({ root, postLaunchReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "closeout-final", "final_decision.md"), "changed\n"); assert.equal(verifyProductionFinalCloseoutReview({ root, document: result }).ok, false); });
test("rejects a fabricated closeout-ready state", () => { const upstream = postLaunch(); const result = buildProductionFinalCloseoutReview({ root: rootFixture(), postLaunchReview: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_closeout"; assert.equal(validateProductionFinalCloseoutReview(result, { postLaunchReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
