import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionExecutionReceiptChecksum, PRODUCTION_EXECUTION_RECEIPT_RECORD_IDS } from "./production-execution-receipt-review.mjs";
import { buildProductionReceiptVerificationReview, productionReceiptVerificationChecksum, validateProductionReceiptVerificationReview, verifyProductionReceiptVerificationReview, PRODUCTION_RECEIPT_VERIFICATION_RECORD_IDS } from "./production-receipt-verification-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-receipt-verification-")); fs.mkdirSync(path.join(root, "work", "verification"), { recursive: true }); for (const id of PRODUCTION_RECEIPT_VERIFICATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "verification", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function receipt(value, status = "pending_production_execution_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_execution_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_execution_receipt" ? PRODUCTION_EXECUTION_RECEIPT_RECORD_IDS.map((id) => ({ id, reference: `work/receipts/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_execution_receipt_checksum: "" }; result.production_execution_receipt_checksum = productionExecutionReceiptChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_RECEIPT_VERIFICATION_RECORD_IDS.map((id) => [id, { reference: `work/verification/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until execution receipts are ready", () => { const value = manifest(); const result = buildProductionReceiptVerificationReview({ root: rootFixture(), manifest: value, productionExecutionReceiptReview: receipt(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_execution_receipt"); });
test("accepts thirty-five receipt-verification records", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_production_execution_receipt"); const result = buildProductionReceiptVerificationReview({ root, manifest: value, productionExecutionReceiptReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_receipt_verification"); assert.equal(validateProductionReceiptVerificationReview(result, { manifest: value, productionExecutionReceiptReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_receipt_verification_checksum, productionReceiptVerificationChecksum(result)); assert.equal(verifyProductionReceiptVerificationReview({ root, document: result }).ok, true); });
test("detects a changed verification record", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_production_execution_receipt"); const result = buildProductionReceiptVerificationReview({ root, manifest: value, productionExecutionReceiptReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "verification", "database_match.md"), "changed\n"); assert.equal(verifyProductionReceiptVerificationReview({ root, document: result }).ok, false); });
test("rejects a fabricated verification state", () => { const value = manifest(); const review = receipt(value); const result = buildProductionReceiptVerificationReview({ root: rootFixture(), manifest: value, productionExecutionReceiptReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_receipt_verification"; assert.equal(validateProductionReceiptVerificationReview(result, { manifest: value, productionExecutionReceiptReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
