import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionExecutionReadinessChecksum, PRODUCTION_EXECUTION_READINESS_RECORD_IDS } from "./production-execution-readiness-review.mjs";
import { buildProductionExecutionReview, productionExecutionChecksum, validateProductionExecutionReview, verifyProductionExecutionReview, PRODUCTION_EXECUTION_RECORD_IDS } from "./production-execution-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-execution-review-")); fs.mkdirSync(path.join(root, "work", "execution"), { recursive: true }); for (const id of PRODUCTION_EXECUTION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "execution", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function readiness(value, status = "pending_production_authorization") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_authorization_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_execution" ? PRODUCTION_EXECUTION_READINESS_RECORD_IDS.map((id) => ({ id, reference: `work/readiness/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_execution_readiness_checksum: "" }; result.production_execution_readiness_checksum = productionExecutionReadinessChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_EXECUTION_RECORD_IDS.map((id) => [id, { reference: `work/execution/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until execution readiness is ready", () => { const value = manifest(); const result = buildProductionExecutionReview({ root: rootFixture(), manifest: value, productionExecutionReadinessReview: readiness(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_execution"); });
test("accepts twenty-five production-execution records", () => { const root = rootFixture(); const value = manifest(); const review = readiness(value, "ready_for_production_execution"); const result = buildProductionExecutionReview({ root, manifest: value, productionExecutionReadinessReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_execution_review"); assert.equal(validateProductionExecutionReview(result, { manifest: value, productionExecutionReadinessReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_execution_checksum, productionExecutionChecksum(result)); assert.equal(verifyProductionExecutionReview({ root, document: result }).ok, true); });
test("detects a changed production-execution record", () => { const root = rootFixture(); const value = manifest(); const review = readiness(value, "ready_for_production_execution"); const result = buildProductionExecutionReview({ root, manifest: value, productionExecutionReadinessReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "execution", "migration_record.md"), "changed\n"); assert.equal(verifyProductionExecutionReview({ root, document: result }).ok, false); });
test("rejects a fabricated production-execution state", () => { const value = manifest(); const review = readiness(value); const result = buildProductionExecutionReview({ root: rootFixture(), manifest: value, productionExecutionReadinessReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_execution_review"; assert.equal(validateProductionExecutionReview(result, { manifest: value, productionExecutionReadinessReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
