import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionLaunchReadinessChecksum, PRODUCTION_LAUNCH_RECORD_IDS } from "./production-launch-readiness.mjs";
import { buildLaunchExecutionReview, launchExecutionReviewChecksum, validateLaunchExecutionReview, verifyLaunchExecutionReview, LAUNCH_EXECUTION_RECORD_IDS } from "./production-launch-execution-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-launch-execution-")); fs.mkdirSync(path.join(root, "work", "execution"), { recursive: true }); for (const id of LAUNCH_EXECUTION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "execution", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function readiness(value, status = "pending_production_decision") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_decision_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_launch_window" ? PRODUCTION_LAUNCH_RECORD_IDS.map((id) => ({ id, reference: `work/launch/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_launch_readiness_checksum: "" }; result.production_launch_readiness_checksum = productionLaunchReadinessChecksum(result); return result; }
function records() { return Object.fromEntries(LAUNCH_EXECUTION_RECORD_IDS.map((id) => [id, { reference: `work/execution/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until launch readiness is ready", () => { const value = manifest(); const result = buildLaunchExecutionReview({ root: rootFixture(), manifest: value, launchReadiness: readiness(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_launch_window"); });
test("accepts thirty launch-execution records", () => { const root = rootFixture(); const value = manifest(); const review = readiness(value, "ready_for_launch_window"); const result = buildLaunchExecutionReview({ root, manifest: value, launchReadiness: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_launch_execution_review"); assert.equal(validateLaunchExecutionReview(result, { manifest: value, launchReadiness: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.launch_execution_review_checksum, launchExecutionReviewChecksum(result)); assert.equal(verifyLaunchExecutionReview({ root, document: result }).ok, true); });
test("detects a changed execution record", () => { const root = rootFixture(); const value = manifest(); const review = readiness(value, "ready_for_launch_window"); const result = buildLaunchExecutionReview({ root, manifest: value, launchReadiness: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "execution", "artifact_manifest_verified.md"), "changed\n"); assert.equal(verifyLaunchExecutionReview({ root, document: result }).ok, false); });
test("rejects a fabricated execution-review state", () => { const value = manifest(); const review = readiness(value); const result = buildLaunchExecutionReview({ root: rootFixture(), manifest: value, launchReadiness: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_launch_execution_review"; assert.equal(validateLaunchExecutionReview(result, { manifest: value, launchReadiness: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
