import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { postLaunchMonitoringChecksum, POST_LAUNCH_MONITORING_RECORD_IDS } from "./post-launch-monitoring-review.mjs";
import { buildProductionStabilizationReview, productionStabilizationChecksum, validateProductionStabilizationReview, verifyProductionStabilizationReview, PRODUCTION_STABILIZATION_RECORD_IDS } from "./production-stabilization-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-stabilization-")); fs.mkdirSync(path.join(root, "work", "stabilization"), { recursive: true }); for (const id of PRODUCTION_STABILIZATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "stabilization", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function monitoring(value, status = "pending_launch_observation") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, launch_observation_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_post_launch_review" ? POST_LAUNCH_MONITORING_RECORD_IDS.map((id) => ({ id, reference: `work/monitoring/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], post_launch_monitoring_checksum: "" }; result.post_launch_monitoring_checksum = postLaunchMonitoringChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_STABILIZATION_RECORD_IDS.map((id) => [id, { reference: `work/stabilization/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until post-launch monitoring is ready", () => { const value = manifest(); const result = buildProductionStabilizationReview({ root: rootFixture(), manifest: value, postLaunchMonitoringReview: monitoring(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_post_launch_review"); });
test("accepts fifteen production-stabilization records", () => { const root = rootFixture(); const value = manifest(); const review = monitoring(value, "ready_for_post_launch_review"); const result = buildProductionStabilizationReview({ root, manifest: value, postLaunchMonitoringReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_stabilization_review"); assert.equal(validateProductionStabilizationReview(result, { manifest: value, postLaunchMonitoringReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_stabilization_checksum, productionStabilizationChecksum(result)); assert.equal(verifyProductionStabilizationReview({ root, document: result }).ok, true); });
test("detects a changed stabilization record", () => { const root = rootFixture(); const value = manifest(); const review = monitoring(value, "ready_for_post_launch_review"); const result = buildProductionStabilizationReview({ root, manifest: value, postLaunchMonitoringReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "stabilization", "rollback_rehearsal_review.md"), "changed\n"); assert.equal(verifyProductionStabilizationReview({ root, document: result }).ok, false); });
test("rejects a fabricated stabilization state", () => { const value = manifest(); const review = monitoring(value); const result = buildProductionStabilizationReview({ root: rootFixture(), manifest: value, postLaunchMonitoringReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_stabilization_review"; assert.equal(validateProductionStabilizationReview(result, { manifest: value, postLaunchMonitoringReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
