import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionLaunchReadinessReview, productionLaunchReadinessChecksum, validateProductionLaunchReadinessReview, verifyProductionLaunchReadinessReview, PRODUCTION_LAUNCH_RECORD_IDS } from "./production-launch-readiness-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-launch-readiness-")); fs.mkdirSync(path.join(root, "work", "launch"), { recursive: true }); for (const id of PRODUCTION_LAUNCH_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "launch", `${id}.md`), `${id} record\n`); return root; }
function reconciliation(status = "pending_evidence_matrix") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", production_evidence_reconciliation_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_LAUNCH_RECORD_IDS.map((id) => [id, { reference: `work/launch/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until reconciliation is ready", () => { const result = buildProductionLaunchReadinessReview({ root: rootFixture(), reconciliationReview: reconciliation(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_reconciliation_review"); assert.equal(PRODUCTION_LAUNCH_RECORD_IDS.length, 35); });
test("accepts thirty-five launch records", () => { const root = rootFixture(); const upstream = reconciliation("ready_for_production_reconciliation"); const result = buildProductionLaunchReadinessReview({ root, reconciliationReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_launch"); assert.equal(validateProductionLaunchReadinessReview(result, { reconciliationReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_launch_readiness_checksum, productionLaunchReadinessChecksum(result)); assert.equal(verifyProductionLaunchReadinessReview({ root, document: result }).ok, true); });
test("detects a changed launch record", () => { const root = rootFixture(); const upstream = reconciliation("ready_for_production_reconciliation"); const result = buildProductionLaunchReadinessReview({ root, reconciliationReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "launch", "rls_probe.md"), "changed\n"); assert.equal(verifyProductionLaunchReadinessReview({ root, document: result }).ok, false); });
test("rejects a fabricated launch-ready state", () => { const upstream = reconciliation(); const result = buildProductionLaunchReadinessReview({ root: rootFixture(), reconciliationReview: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_launch"; assert.equal(validateProductionLaunchReadinessReview(result, { reconciliationReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
