import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionCloseoutChecksum, PRODUCTION_CLOSEOUT_RECORD_IDS } from "./production-closeout-review.mjs";
import { buildProductionReconciliationReview, productionReconciliationChecksum, validateProductionReconciliationReview, verifyProductionReconciliationReview, PRODUCTION_RECONCILIATION_RECORD_IDS } from "./production-reconciliation-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-reconciliation-")); fs.mkdirSync(path.join(root, "work", "reconciliation"), { recursive: true }); for (const id of PRODUCTION_RECONCILIATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "reconciliation", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function closeout(value, status = "pending_production_stabilization_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_stabilization_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_closeout_review" ? PRODUCTION_CLOSEOUT_RECORD_IDS.map((id) => ({ id, reference: `work/closeout/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_closeout_checksum: "" }; result.production_closeout_checksum = productionCloseoutChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_RECONCILIATION_RECORD_IDS.map((id) => [id, { reference: `work/reconciliation/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until closeout is ready", () => { const value = manifest(); const result = buildProductionReconciliationReview({ root: rootFixture(), manifest: value, productionCloseoutReview: closeout(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_closeout_review"); });
test("accepts fifteen reconciliation records", () => { const root = rootFixture(); const value = manifest(); const review = closeout(value, "ready_for_production_closeout_review"); const result = buildProductionReconciliationReview({ root, manifest: value, productionCloseoutReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_reconciliation"); assert.equal(validateProductionReconciliationReview(result, { manifest: value, productionCloseoutReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_reconciliation_checksum, productionReconciliationChecksum(result)); assert.equal(verifyProductionReconciliationReview({ root, document: result }).ok, true); });
test("detects a changed reconciliation record", () => { const root = rootFixture(); const value = manifest(); const review = closeout(value, "ready_for_production_closeout_review"); const result = buildProductionReconciliationReview({ root, manifest: value, productionCloseoutReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "reconciliation", "google_drive_receipt.md"), "changed\n"); assert.equal(verifyProductionReconciliationReview({ root, document: result }).ok, false); });
test("rejects a fabricated reconciliation state", () => { const value = manifest(); const review = closeout(value); const result = buildProductionReconciliationReview({ root: rootFixture(), manifest: value, productionCloseoutReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_reconciliation"; assert.equal(validateProductionReconciliationReview(result, { manifest: value, productionCloseoutReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
