import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionPostLaunchReview, productionPostLaunchChecksum, validateProductionPostLaunchReview, verifyProductionPostLaunchReview, PRODUCTION_POST_LAUNCH_RECORD_IDS } from "./production-post-launch-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-post-launch-")); fs.mkdirSync(path.join(root, "work", "post-launch"), { recursive: true }); for (const id of PRODUCTION_POST_LAUNCH_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "post-launch", `${id}.md`), `${id} record\n`); return root; }
function readiness(status = "pending_reconciliation_review") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", production_launch_readiness_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_POST_LAUNCH_RECORD_IDS.map((id) => [id, { reference: `work/post-launch/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until launch readiness is ready", () => { const result = buildProductionPostLaunchReview({ root: rootFixture(), launchReadiness: readiness(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_launch_readiness"); assert.equal(PRODUCTION_POST_LAUNCH_RECORD_IDS.length, 100); });
test("accepts one hundred post-launch records", () => { const root = rootFixture(); const upstream = readiness("ready_for_production_launch"); const result = buildProductionPostLaunchReview({ root, launchReadiness: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_post_launch_review"); assert.equal(Object.values(result.groups).reduce((sum, value) => sum + value, 0), 100); assert.equal(validateProductionPostLaunchReview(result, { launchReadiness: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_post_launch_checksum, productionPostLaunchChecksum(result)); assert.equal(verifyProductionPostLaunchReview({ root, document: result }).ok, true); });
test("detects a changed post-launch record", () => { const root = rootFixture(); const upstream = readiness("ready_for_production_launch"); const result = buildProductionPostLaunchReview({ root, launchReadiness: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "post-launch", "error_rate.md"), "changed\n"); assert.equal(verifyProductionPostLaunchReview({ root, document: result }).ok, false); });
test("rejects a fabricated post-launch-ready state", () => { const upstream = readiness(); const result = buildProductionPostLaunchReview({ root: rootFixture(), launchReadiness: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_post_launch_review"; assert.equal(validateProductionPostLaunchReview(result, { launchReadiness: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
