import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionStabilizationChecksum, PRODUCTION_STABILIZATION_RECORD_IDS } from "./production-stabilization-review.mjs";
import { buildProductionCloseoutReview, productionCloseoutChecksum, validateProductionCloseoutReview, verifyProductionCloseoutReview, PRODUCTION_CLOSEOUT_RECORD_IDS } from "./production-closeout-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-closeout-")); fs.mkdirSync(path.join(root, "work", "closeout"), { recursive: true }); for (const id of PRODUCTION_CLOSEOUT_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "closeout", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function stabilization(value, status = "pending_post_launch_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, post_launch_monitoring_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_stabilization_review" ? PRODUCTION_STABILIZATION_RECORD_IDS.map((id) => ({ id, reference: `work/stabilization/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_stabilization_checksum: "" }; result.production_stabilization_checksum = productionStabilizationChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_CLOSEOUT_RECORD_IDS.map((id) => [id, { reference: `work/closeout/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until stabilization is ready", () => { const value = manifest(); const result = buildProductionCloseoutReview({ root: rootFixture(), manifest: value, productionStabilizationReview: stabilization(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_stabilization_review"); });
test("accepts twenty production-closeout records", () => { const root = rootFixture(); const value = manifest(); const review = stabilization(value, "ready_for_production_stabilization_review"); const result = buildProductionCloseoutReview({ root, manifest: value, productionStabilizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_closeout_review"); assert.equal(validateProductionCloseoutReview(result, { manifest: value, productionStabilizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_closeout_checksum, productionCloseoutChecksum(result)); assert.equal(verifyProductionCloseoutReview({ root, document: result }).ok, true); });
test("detects a changed closeout record", () => { const root = rootFixture(); const value = manifest(); const review = stabilization(value, "ready_for_production_stabilization_review"); const result = buildProductionCloseoutReview({ root, manifest: value, productionStabilizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "closeout", "security_log_attestation.md"), "changed\n"); assert.equal(verifyProductionCloseoutReview({ root, document: result }).ok, false); });
test("rejects a fabricated closeout state", () => { const value = manifest(); const review = stabilization(value); const result = buildProductionCloseoutReview({ root: rootFixture(), manifest: value, productionStabilizationReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_closeout_review"; assert.equal(validateProductionCloseoutReview(result, { manifest: value, productionStabilizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
