import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionEvidenceReconciliationReview, productionEvidenceReconciliationChecksum, validateProductionEvidenceReconciliationReview, verifyProductionEvidenceReconciliationReview, PRODUCTION_RECONCILIATION_RECORD_IDS } from "./production-evidence-reconciliation-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-reconciliation-")); fs.mkdirSync(path.join(root, "work", "reconciliation"), { recursive: true }); for (const id of PRODUCTION_RECONCILIATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "reconciliation", `${id}.md`), `${id} record\n`); return root; }
function matrix(status = "pending_environment_review") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", production_evidence_matrix_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_RECONCILIATION_RECORD_IDS.map((id) => [id, { reference: `work/reconciliation/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until the evidence matrix is ready", () => { const result = buildProductionEvidenceReconciliationReview({ root: rootFixture(), evidenceMatrix: matrix(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_evidence_matrix"); assert.equal(PRODUCTION_RECONCILIATION_RECORD_IDS.length, 25); });
test("accepts twenty-five reconciliation records", () => { const root = rootFixture(); const upstream = matrix("ready_for_production_evidence"); const result = buildProductionEvidenceReconciliationReview({ root, evidenceMatrix: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_reconciliation"); assert.equal(validateProductionEvidenceReconciliationReview(result, { evidenceMatrix: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_evidence_reconciliation_checksum, productionEvidenceReconciliationChecksum(result)); assert.equal(verifyProductionEvidenceReconciliationReview({ root, document: result }).ok, true); });
test("detects a changed reconciliation record", () => { const root = rootFixture(); const upstream = matrix("ready_for_production_evidence"); const result = buildProductionEvidenceReconciliationReview({ root, evidenceMatrix: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "reconciliation", "drive_receipt.md"), "changed\n"); assert.equal(verifyProductionEvidenceReconciliationReview({ root, document: result }).ok, false); });
test("rejects a fabricated reconciliation-ready state", () => { const upstream = matrix(); const result = buildProductionEvidenceReconciliationReview({ root: rootFixture(), evidenceMatrix: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_reconciliation"; assert.equal(validateProductionEvidenceReconciliationReview(result, { evidenceMatrix: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
