import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionAuthorizationChecksum, PRODUCTION_AUTHORIZATION_RECORD_IDS } from "./production-authorization-review.mjs";
import { buildProductionExecutionReadinessReview, productionExecutionReadinessChecksum, validateProductionExecutionReadinessReview, verifyProductionExecutionReadinessReview, PRODUCTION_EXECUTION_READINESS_RECORD_IDS } from "./production-execution-readiness-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-execution-")); fs.mkdirSync(path.join(root, "work", "execution-readiness"), { recursive: true }); for (const id of PRODUCTION_EXECUTION_READINESS_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "execution-readiness", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function authorization(value, status = "pending_production_reconciliation") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_reconciliation_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_authorization" ? PRODUCTION_AUTHORIZATION_RECORD_IDS.map((id) => ({ id, reference: `work/authorization/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_authorization_checksum: "" }; result.production_authorization_checksum = productionAuthorizationChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_EXECUTION_READINESS_RECORD_IDS.map((id) => [id, { reference: `work/execution-readiness/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until authorization is ready", () => { const value = manifest(); const result = buildProductionExecutionReadinessReview({ root: rootFixture(), manifest: value, productionAuthorizationReview: authorization(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_authorization"); });
test("accepts twenty-five execution-readiness records", () => { const root = rootFixture(); const value = manifest(); const review = authorization(value, "ready_for_production_authorization"); const result = buildProductionExecutionReadinessReview({ root, manifest: value, productionAuthorizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_execution"); assert.equal(validateProductionExecutionReadinessReview(result, { manifest: value, productionAuthorizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_execution_readiness_checksum, productionExecutionReadinessChecksum(result)); assert.equal(verifyProductionExecutionReadinessReview({ root, document: result }).ok, true); });
test("detects a changed execution-readiness record", () => { const root = rootFixture(); const value = manifest(); const review = authorization(value, "ready_for_production_authorization"); const result = buildProductionExecutionReadinessReview({ root, manifest: value, productionAuthorizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "execution-readiness", "migration_backup.md"), "changed\n"); assert.equal(verifyProductionExecutionReadinessReview({ root, document: result }).ok, false); });
test("rejects a fabricated execution state", () => { const value = manifest(); const review = authorization(value); const result = buildProductionExecutionReadinessReview({ root: rootFixture(), manifest: value, productionAuthorizationReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_execution"; assert.equal(validateProductionExecutionReadinessReview(result, { manifest: value, productionAuthorizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
