import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionPrerequisites } from "./production-prerequisites.mjs";
import { buildProductionPrerequisiteReview, productionPrerequisiteReviewChecksum, validateProductionPrerequisiteReview, verifyProductionPrerequisiteReview, PREREQUISITE_RECORD_IDS } from "./production-prerequisite-review.mjs";
const ENV = { NODE_ENV: "production", DEMO_MODE: "false", PUBLIC_ORIGIN: "https://portal.mgt-skin-care.test", DATABASE_URL: "postgresql://u:p@db.mgt-skin-care.test:5432/postgres?sslmode=verify-full", PORTAL_AUTO_MIGRATE: "false", PORTAL_DOMAIN: "portal.mgt-skin-care.test", NODE_IMAGE: "node@sha256:" + "a".repeat(64), API_IMAGE: "ghcr.io/mgt/api@sha256:" + "d".repeat(64), WEB_IMAGE: "ghcr.io/mgt/web@sha256:" + "e".repeat(64), OLLAMA_IMAGE: "ollama/ollama@sha256:" + "b".repeat(64), CADDY_IMAGE: "caddy@sha256:" + "c".repeat(64), SUPABASE_URL: "https://project.supabase.co", SUPABASE_ANON_KEY: "anon", SUPABASE_SERVICE_ROLE_KEY: "service", OLLAMA_ENABLED: "true", OLLAMA_BASE_URL: "https://ollama.mgt-skin-care.test", OPENCLAW_ENABLED: "false", WORKER_INTERVAL_SECONDS: "60", WORKER_READINESS_MAX_AGE_SECONDS: "300", BACKUP_MAX_AGE_HOURS: "26", BACKUP_RESTORE_MAX_AGE_DAYS: "90", NOTIFICATION_DELIVERY: "in_app", SUPPORT_OWNER_NAME: "Support Owner", SUPPORT_OWNER_EMAIL: "support@mgt-skin-care.test", ACCESSIBILITY_VALIDATION_REPORT_URL: "https://evidence.mgt-skin-care.test/accessibility", ACCESSIBILITY_VALIDATED_AT: "2026-01-01T00:00:00.000Z", MONITORING_DASHBOARD_URL: "https://monitoring.mgt-skin-care.test/dashboard", INCIDENT_RUNBOOK_URL: "https://operations.mgt-skin-care.test/runbook", ALERT_OWNER_EMAIL: "alerts@mgt-skin-care.test", SUPPORT_RESPONSE_TARGET_HOURS: "24", SUBSCRIPTIONS_ENABLED: "false" };
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-prerequisite-review-")); fs.mkdirSync(path.join(root, "work", "prerequisites"), { recursive: true }); for (const id of PREREQUISITE_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "prerequisites", `${id}.md`), `${id} record\n`); return root; }
function records() { return Object.fromEntries(PREREQUISITE_RECORD_IDS.map((id) => [id, { reference: `work/prerequisites/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
function prerequisites() { return buildProductionPrerequisites({ env: ENV, candidateCommit: "0123456789abcdef0123456789abcdef01234567" }); }
test("stays pending until the ten prerequisite records exist", () => { const p = prerequisites(); const result = buildProductionPrerequisiteReview({ root: rootFixture(), prerequisites: p, now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_external_prerequisites"); });
test("accepts ten prerequisite records", () => { const root = rootFixture(); const p = prerequisites(); const result = buildProductionPrerequisiteReview({ root, prerequisites: p, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_prerequisite_review"); assert.equal(validateProductionPrerequisiteReview(result, { prerequisites: p, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.prerequisite_review_checksum, productionPrerequisiteReviewChecksum(result)); assert.equal(verifyProductionPrerequisiteReview({ root, document: result }).ok, true); });
test("detects a changed prerequisite record", () => { const root = rootFixture(); const p = prerequisites(); const result = buildProductionPrerequisiteReview({ root, prerequisites: p, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "prerequisites", "database_target.md"), "changed\n"); assert.equal(verifyProductionPrerequisiteReview({ root, document: result }).ok, false); });
test("rejects a fabricated ready state", () => { const p = prerequisites(); const result = buildProductionPrerequisiteReview({ root: rootFixture(), prerequisites: p, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_prerequisite_review"; assert.equal(validateProductionPrerequisiteReview(result, { prerequisites: p, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); assert.equal(result.entries.length, 0); });
