import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { productionExecutionChecksum, PRODUCTION_EXECUTION_RECORD_IDS } from "./production-execution-review.mjs";
import { buildProductionExecutionReceiptReview, productionExecutionReceiptChecksum, validateProductionExecutionReceiptReview, verifyProductionExecutionReceiptReview, PRODUCTION_EXECUTION_RECEIPT_RECORD_IDS } from "./production-execution-receipt-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-receipt-")); fs.mkdirSync(path.join(root, "work", "receipts"), { recursive: true }); for (const id of PRODUCTION_EXECUTION_RECEIPT_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "receipts", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function execution(value, status = "pending_production_execution") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_execution_readiness_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_production_execution_review" ? PRODUCTION_EXECUTION_RECORD_IDS.map((id) => ({ id, reference: `work/execution/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], production_execution_checksum: "" }; result.production_execution_checksum = productionExecutionChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_EXECUTION_RECEIPT_RECORD_IDS.map((id) => [id, { reference: `work/receipts/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until production execution is ready", () => { const value = manifest(); const result = buildProductionExecutionReceiptReview({ root: rootFixture(), manifest: value, productionExecutionReview: execution(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_production_execution_review"); });
test("accepts twenty-five production-execution receipts", () => { const root = rootFixture(); const value = manifest(); const review = execution(value, "ready_for_production_execution_review"); const result = buildProductionExecutionReceiptReview({ root, manifest: value, productionExecutionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_execution_receipt"); assert.equal(validateProductionExecutionReceiptReview(result, { manifest: value, productionExecutionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_execution_receipt_checksum, productionExecutionReceiptChecksum(result)); assert.equal(verifyProductionExecutionReceiptReview({ root, document: result }).ok, true); });
test("detects a changed execution receipt", () => { const root = rootFixture(); const value = manifest(); const review = execution(value, "ready_for_production_execution_review"); const result = buildProductionExecutionReceiptReview({ root, manifest: value, productionExecutionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "receipts", "deployment_receipt.md"), "changed\n"); assert.equal(verifyProductionExecutionReceiptReview({ root, document: result }).ok, false); });
test("rejects a fabricated receipt state", () => { const value = manifest(); const review = execution(value); const result = buildProductionExecutionReceiptReview({ root: rootFixture(), manifest: value, productionExecutionReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_execution_receipt"; assert.equal(validateProductionExecutionReceiptReview(result, { manifest: value, productionExecutionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
