import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionEvidenceMatrixReview, productionEvidenceMatrixChecksum, validateProductionEvidenceMatrixReview, verifyProductionEvidenceMatrixReview, PRODUCTION_EVIDENCE_RECORD_IDS } from "./production-evidence-matrix-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-evidence-matrix-")); fs.mkdirSync(path.join(root, "work", "evidence"), { recursive: true }); for (const id of PRODUCTION_EVIDENCE_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "evidence", `${id}.md`), `${id} evidence\n`); return root; }
function environment(status = "pending_prerequisite_review") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", production_environment_review_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_EVIDENCE_RECORD_IDS.map((id) => [id, { reference: `work/evidence/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until environment review is ready", () => { const result = buildProductionEvidenceMatrixReview({ root: rootFixture(), environmentReview: environment(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_environment_review"); assert.equal(PRODUCTION_EVIDENCE_RECORD_IDS.length, 100); });
test("accepts one hundred evidence records", () => { const root = rootFixture(); const upstream = environment("ready_for_production_environment"); const result = buildProductionEvidenceMatrixReview({ root, environmentReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_evidence"); assert.equal(Object.values(result.groups).reduce((sum, value) => sum + value, 0), 100); assert.equal(validateProductionEvidenceMatrixReview(result, { environmentReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_evidence_matrix_checksum, productionEvidenceMatrixChecksum(result)); assert.equal(verifyProductionEvidenceMatrixReview({ root, document: result }).ok, true); });
test("detects changed evidence", () => { const root = rootFixture(); const upstream = environment("ready_for_production_environment"); const result = buildProductionEvidenceMatrixReview({ root, environmentReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "evidence", "rls_policy.md"), "changed\n"); assert.equal(verifyProductionEvidenceMatrixReview({ root, document: result }).ok, false); });
test("rejects a fabricated matrix-ready state", () => { const upstream = environment(); const result = buildProductionEvidenceMatrixReview({ root: rootFixture(), environmentReview: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_evidence"; assert.equal(validateProductionEvidenceMatrixReview(result, { environmentReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
