import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildProductionEnvironmentReview, productionEnvironmentReviewChecksum, validateProductionEnvironmentReview, verifyProductionEnvironmentReview, PRODUCTION_ENVIRONMENT_RECORD_IDS } from "./production-environment-review.mjs";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-environment-review-")); fs.mkdirSync(path.join(root, "work", "environment"), { recursive: true }); for (const id of PRODUCTION_ENVIRONMENT_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "environment", `${id}.md`), `${id} record\n`); return root; }
function prerequisite(status = "pending_external_prerequisites") { return { candidate_commit: "0123456789abcdef0123456789abcdef01234567", prerequisite_review_checksum: "sha256:" + "d".repeat(64), status }; }
function records() { return Object.fromEntries(PRODUCTION_ENVIRONMENT_RECORD_IDS.map((id) => [id, { reference: `work/environment/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until prerequisite review is ready", () => { const result = buildProductionEnvironmentReview({ root: rootFixture(), prerequisiteReview: prerequisite(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_prerequisite_review"); });
test("accepts twenty-five environment records after prerequisites", () => { const root = rootFixture(); const upstream = prerequisite("ready_for_prerequisite_review"); const result = buildProductionEnvironmentReview({ root, prerequisiteReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_environment"); assert.equal(validateProductionEnvironmentReview(result, { prerequisiteReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_environment_review_checksum, productionEnvironmentReviewChecksum(result)); assert.equal(verifyProductionEnvironmentReview({ root, document: result }).ok, true); });
test("detects a changed environment record", () => { const root = rootFixture(); const upstream = prerequisite("ready_for_prerequisite_review"); const result = buildProductionEnvironmentReview({ root, prerequisiteReview: upstream, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "environment", "database_url.md"), "changed\n"); assert.equal(verifyProductionEnvironmentReview({ root, document: result }).ok, false); });
test("rejects a fabricated ready state", () => { const upstream = prerequisite(); const result = buildProductionEnvironmentReview({ root: rootFixture(), prerequisiteReview: upstream, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_environment"; assert.equal(validateProductionEnvironmentReview(result, { prerequisiteReview: upstream, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
