import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { launchExecutionReviewChecksum, LAUNCH_EXECUTION_RECORD_IDS } from "./production-launch-execution-review.mjs";
import { buildLaunchObservationReview, launchObservationReviewChecksum, validateLaunchObservationReview, verifyLaunchObservationReview, LAUNCH_OBSERVATION_RECORD_IDS } from "./production-launch-observation-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-launch-observation-")); fs.mkdirSync(path.join(root, "work", "observation"), { recursive: true }); for (const id of LAUNCH_OBSERVATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "observation", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function execution(value, status = "pending_launch_window") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, production_launch_readiness_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_launch_execution_review" ? LAUNCH_EXECUTION_RECORD_IDS.map((id) => ({ id, reference: `work/execution/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], launch_execution_review_checksum: "" }; result.launch_execution_review_checksum = launchExecutionReviewChecksum(result); return result; }
function records() { return Object.fromEntries(LAUNCH_OBSERVATION_RECORD_IDS.map((id) => [id, { reference: `work/observation/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until launch execution is ready", () => { const value = manifest(); const result = buildLaunchObservationReview({ root: rootFixture(), manifest: value, launchExecutionReview: execution(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_launch_execution_review"); });
test("accepts thirty-five launch-observation records", () => { const root = rootFixture(); const value = manifest(); const review = execution(value, "ready_for_launch_execution_review"); const result = buildLaunchObservationReview({ root, manifest: value, launchExecutionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_launch_observation"); assert.equal(validateLaunchObservationReview(result, { manifest: value, launchExecutionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.launch_observation_review_checksum, launchObservationReviewChecksum(result)); assert.equal(verifyLaunchObservationReview({ root, document: result }).ok, true); });
test("detects a changed observation record", () => { const root = rootFixture(); const value = manifest(); const review = execution(value, "ready_for_launch_execution_review"); const result = buildLaunchObservationReview({ root, manifest: value, launchExecutionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "observation", "route_support.md"), "changed\n"); assert.equal(verifyLaunchObservationReview({ root, document: result }).ok, false); });
test("rejects a fabricated observation state", () => { const value = manifest(); const review = execution(value); const result = buildLaunchObservationReview({ root: rootFixture(), manifest: value, launchExecutionReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_launch_observation"; assert.equal(validateLaunchObservationReview(result, { manifest: value, launchExecutionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
