import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { finalReleaseVerificationChecksum, FINAL_RELEASE_VERIFICATION_RECORD_IDS } from "./final-release-verification.mjs";
import { buildProductionDecisionReview, productionDecisionReviewChecksum, validateProductionDecisionReview, verifyProductionDecisionReview, PRODUCTION_DECISION_RECORD_IDS } from "./production-decision-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-production-decision-")); fs.mkdirSync(path.join(root, "work", "decision"), { recursive: true }); for (const id of PRODUCTION_DECISION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "decision", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function finalReview(value, status = "pending_receipt_verification") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, receipt_verification_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_final_release_review" ? FINAL_RELEASE_VERIFICATION_RECORD_IDS.map((id) => ({ id, reference: `work/final/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], final_release_verification_checksum: "" }; result.final_release_verification_checksum = finalReleaseVerificationChecksum(result); return result; }
function records() { return Object.fromEntries(PRODUCTION_DECISION_RECORD_IDS.map((id) => [id, { reference: `work/decision/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until final-release verification is ready", () => { const value = manifest(); const result = buildProductionDecisionReview({ root: rootFixture(), manifest: value, finalReleaseVerification: finalReview(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_final_release_review"); });
test("accepts twenty production-decision records", () => { const root = rootFixture(); const value = manifest(); const review = finalReview(value, "ready_for_final_release_review"); const result = buildProductionDecisionReview({ root, manifest: value, finalReleaseVerification: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_production_decision"); assert.equal(validateProductionDecisionReview(result, { manifest: value, finalReleaseVerification: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.production_decision_review_checksum, productionDecisionReviewChecksum(result)); assert.equal(verifyProductionDecisionReview({ root, document: result }).ok, true); });
test("detects a changed decision record", () => { const root = rootFixture(); const value = manifest(); const review = finalReview(value, "ready_for_final_release_review"); const result = buildProductionDecisionReview({ root, manifest: value, finalReleaseVerification: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "decision", "rollback_decision.md"), "changed\n"); assert.equal(verifyProductionDecisionReview({ root, document: result }).ok, false); });
test("rejects a fabricated production-decision state", () => { const value = manifest(); const review = finalReview(value); const result = buildProductionDecisionReview({ root: rootFixture(), manifest: value, finalReleaseVerification: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_production_decision"; assert.equal(validateProductionDecisionReview(result, { manifest: value, finalReleaseVerification: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
