import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseDecisionReviewChecksum, RELEASE_DECISION_RECORD_IDS } from "./release-decision-review.mjs";
import { buildReleaseAuthorizationReview, releaseAuthorizationReviewChecksum, validateReleaseAuthorizationReview, verifyReleaseAuthorizationReview, RELEASE_AUTHORIZATION_RECORD_IDS } from "./release-authorization-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-authorization-review-")); fs.mkdirSync(path.join(root, "work", "authorization"), { recursive: true }); for (const id of RELEASE_AUTHORIZATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "authorization", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function decision(value, status = "pending_closure_approval") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, closure_approval_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_release_authorization" ? RELEASE_DECISION_RECORD_IDS.map((id) => ({ id, reference: `work/decision/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], decision_review_checksum: "" }; result.decision_review_checksum = releaseDecisionReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_AUTHORIZATION_RECORD_IDS.map((id) => [id, { reference: `work/authorization/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until decision review is ready", () => { const value = manifest(); const result = buildReleaseAuthorizationReview({ root: rootFixture(), manifest: value, decisionReview: decision(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_decision_review"); });
test("accepts fifteen authorization records", () => { const root = rootFixture(); const value = manifest(); const review = decision(value, "ready_for_release_authorization"); const result = buildReleaseAuthorizationReview({ root, manifest: value, decisionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_operator_authorization"); assert.equal(validateReleaseAuthorizationReview(result, { manifest: value, decisionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.authorization_review_checksum, releaseAuthorizationReviewChecksum(result)); assert.equal(verifyReleaseAuthorizationReview({ root, document: result }).ok, true); });
test("detects a changed authorization record", () => { const root = rootFixture(); const value = manifest(); const review = decision(value, "ready_for_release_authorization"); const result = buildReleaseAuthorizationReview({ root, manifest: value, decisionReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "authorization", "credential_boundary.md"), "changed\n"); assert.equal(verifyReleaseAuthorizationReview({ root, document: result }).ok, false); });
test("rejects a fabricated operator-authorization state", () => { const value = manifest(); const review = decision(value); const result = buildReleaseAuthorizationReview({ root: rootFixture(), manifest: value, decisionReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_operator_authorization"; assert.equal(validateReleaseAuthorizationReview(result, { manifest: value, decisionReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
