import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseExecutionReceiptReviewChecksum, RELEASE_EXECUTION_RECEIPT_RECORD_IDS } from "./release-execution-receipt-review.mjs";
import { buildReleaseExecutionIntakeReview, releaseExecutionIntakeReviewChecksum, validateReleaseExecutionIntakeReview, verifyReleaseExecutionIntakeReview, RELEASE_EXECUTION_INTAKE_RECORD_IDS } from "./release-execution-intake-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-execution-intake-")); fs.mkdirSync(path.join(root, "work", "intake"), { recursive: true }); for (const id of RELEASE_EXECUTION_INTAKE_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "intake", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function receipt(value, status = "pending_execution_request") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, execution_request_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_execution_receipt" ? RELEASE_EXECUTION_RECEIPT_RECORD_IDS.map((id) => ({ id, reference: `work/receipt/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], execution_receipt_review_checksum: "" }; result.execution_receipt_review_checksum = releaseExecutionReceiptReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_EXECUTION_INTAKE_RECORD_IDS.map((id) => [id, { reference: `work/intake/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until execution-receipt review is ready", () => { const value = manifest(); const result = buildReleaseExecutionIntakeReview({ root: rootFixture(), manifest: value, executionReceiptReview: receipt(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_execution_receipt"); });
test("accepts twelve execution-intake records", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_execution_receipt"); const result = buildReleaseExecutionIntakeReview({ root, manifest: value, executionReceiptReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_external_execution_intake"); assert.equal(validateReleaseExecutionIntakeReview(result, { manifest: value, executionReceiptReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.execution_intake_review_checksum, releaseExecutionIntakeReviewChecksum(result)); assert.equal(verifyReleaseExecutionIntakeReview({ root, document: result }).ok, true); });
test("detects a changed execution-intake record", () => { const root = rootFixture(); const value = manifest(); const review = receipt(value, "ready_for_execution_receipt"); const result = buildReleaseExecutionIntakeReview({ root, manifest: value, executionReceiptReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "intake", "health_probe_result.md"), "changed\n"); assert.equal(verifyReleaseExecutionIntakeReview({ root, document: result }).ok, false); });
test("rejects a fabricated external-intake state", () => { const value = manifest(); const review = receipt(value); const result = buildReleaseExecutionIntakeReview({ root: rootFixture(), manifest: value, executionReceiptReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_external_execution_intake"; assert.equal(validateReleaseExecutionIntakeReview(result, { manifest: value, executionReceiptReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
