import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { buildReleasePostExecutionReview, releasePostExecutionReviewChecksum, validateReleasePostExecutionReview, verifyReleasePostExecutionReview, POST_EXECUTION_RECORD_IDS } from "./release-post-execution-review.mjs";
import { releaseExecutionReviewChecksum, EXECUTION_RECORD_IDS } from "./release-execution-review.mjs";

const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-post-execution-")); fs.mkdirSync(path.join(root, "work", "post-execution"), { recursive: true }); for (const id of POST_EXECUTION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "post-execution", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function execution(value, status = "pending_launch_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, launch_review_checksum: "sha256:" + "e".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_execution_review" ? EXECUTION_RECORD_IDS.map((id) => ({ id, reference: `work/execution/${id}.md`, checksum: "sha256:" + "d".repeat(64), bytes: 1 })) : [], errors: [] }; result.execution_review_checksum = releaseExecutionReviewChecksum(result); return result; }
function records() { return Object.fromEntries(POST_EXECUTION_RECORD_IDS.map((id) => [id, { reference: `work/post-execution/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }

test("stays pending until execution review is ready", () => { const value = manifest(); const result = buildReleasePostExecutionReview({ root: rootFixture(), manifest: value, executionReview: execution(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_execution_review"); });
test("accepts twelve post-execution records", () => { const root = rootFixture(); const value = manifest(); const result = buildReleasePostExecutionReview({ root, manifest: value, executionReview: execution(value, "ready_for_execution_review"), records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_post_execution_review"); assert.equal(validateReleasePostExecutionReview(result, { manifest: value, executionReview: execution(value, "ready_for_execution_review"), now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.post_execution_review_checksum, releasePostExecutionReviewChecksum(result)); assert.equal(verifyReleasePostExecutionReview({ root, document: result }).ok, true); });
test("detects a changed post-execution record", () => { const root = rootFixture(); const value = manifest(); const result = buildReleasePostExecutionReview({ root, manifest: value, executionReview: execution(value, "ready_for_execution_review"), records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "post-execution", "health_probe.md"), "changed\n"); assert.equal(verifyReleasePostExecutionReview({ root, document: result }).ok, false); });
test("rejects a fabricated ready state", () => { const value = manifest(); const result = buildReleasePostExecutionReview({ root: rootFixture(), manifest: value, executionReview: execution(value), now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_post_execution_review"; assert.equal(validateReleasePostExecutionReview(result, { manifest: value, executionReview: execution(value), now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
