import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { buildReleaseClosureApproval, releaseClosureApprovalChecksum, validateReleaseClosureApproval, verifyReleaseClosureApproval, CLOSURE_APPROVAL_RECORD_IDS } from "./release-closure-approval.mjs";
import { releaseClosureReviewChecksum, CLOSURE_RECORD_IDS } from "./release-closure-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-closure-approval-")); fs.mkdirSync(path.join(root, "work", "approval"), { recursive: true }); for (const id of CLOSURE_APPROVAL_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "approval", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function closure(value, status = "pending_post_execution_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, post_execution_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_closure_review" ? CLOSURE_RECORD_IDS.map((id) => ({ id, reference: `work/closure/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], closure_review_checksum: "" }; result.closure_review_checksum = releaseClosureReviewChecksum(result); return result; }
function records() { return Object.fromEntries(CLOSURE_APPROVAL_RECORD_IDS.map((id) => [id, { reference: `work/approval/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until closure review is ready", () => { const value = manifest(); const result = buildReleaseClosureApproval({ root: rootFixture(), manifest: value, closureReview: closure(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_closure_review"); });
test("accepts ten approval records", () => { const root = rootFixture(); const value = manifest(); const review = closure(value, "ready_for_closure_review"); const result = buildReleaseClosureApproval({ root, manifest: value, closureReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_release_decision"); assert.equal(validateReleaseClosureApproval(result, { manifest: value, closureReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.closure_approval_checksum, releaseClosureApprovalChecksum(result)); assert.equal(verifyReleaseClosureApproval({ root, document: result }).ok, true); });
test("detects a changed approval record", () => { const root = rootFixture(); const value = manifest(); const review = closure(value, "ready_for_closure_review"); const result = buildReleaseClosureApproval({ root, manifest: value, closureReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "approval", "monitoring_window.md"), "changed\n"); assert.equal(verifyReleaseClosureApproval({ root, document: result }).ok, false); });
test("rejects a fabricated ready state", () => { const value = manifest(); const review = closure(value); const result = buildReleaseClosureApproval({ root: rootFixture(), manifest: value, closureReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_release_decision"; assert.equal(validateReleaseClosureApproval(result, { manifest: value, closureReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
