import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { buildReleaseClosureReview, releaseClosureReviewChecksum, validateReleaseClosureReview, verifyReleaseClosureReview, CLOSURE_RECORD_IDS } from "./release-closure-review.mjs";
import { releasePostExecutionReviewChecksum, POST_EXECUTION_RECORD_IDS } from "./release-post-execution-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-closure-review-")); fs.mkdirSync(path.join(root, "work", "closure"), { recursive: true }); for (const id of CLOSURE_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "closure", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function post(value, status = "pending_execution_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, execution_review_checksum: "sha256:" + "e".repeat(64), post_execution_review_checksum: "", status, generated_at: "2026-01-01T01:00:00.000Z", entries: status === "ready_for_post_execution_review" ? POST_EXECUTION_RECORD_IDS.map((id) => ({ id, reference: `work/post-execution/${id}.md`, checksum: "sha256:" + "d".repeat(64), bytes: 1 })) : [], errors: [] }; result.post_execution_review_checksum = releasePostExecutionReviewChecksum(result); return result; }
function records() { return Object.fromEntries(CLOSURE_RECORD_IDS.map((id) => [id, { reference: `work/closure/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until post-execution review is ready", () => { const value = manifest(); const result = buildReleaseClosureReview({ root: rootFixture(), manifest: value, postExecutionReview: post(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_post_execution_review"); });
test("accepts twelve closure records", () => { const root = rootFixture(); const value = manifest(); const result = buildReleaseClosureReview({ root, manifest: value, postExecutionReview: post(value, "ready_for_post_execution_review"), records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_closure_review"); assert.equal(validateReleaseClosureReview(result, { manifest: value, postExecutionReview: post(value, "ready_for_post_execution_review"), now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.closure_review_checksum, releaseClosureReviewChecksum(result)); assert.equal(verifyReleaseClosureReview({ root, document: result }).ok, true); });
test("detects a changed closure record", () => { const root = rootFixture(); const value = manifest(); const result = buildReleaseClosureReview({ root, manifest: value, postExecutionReview: post(value, "ready_for_post_execution_review"), records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "closure", "security_review.md"), "changed\n"); assert.equal(verifyReleaseClosureReview({ root, document: result }).ok, false); });
test("rejects a fabricated ready state", () => { const value = manifest(); const result = buildReleaseClosureReview({ root: rootFixture(), manifest: value, postExecutionReview: post(value), now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_closure_review"; assert.equal(validateReleaseClosureReview(result, { manifest: value, postExecutionReview: post(value), now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
