import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseClosureApprovalChecksum, CLOSURE_APPROVAL_RECORD_IDS } from "./release-closure-approval.mjs";
import { buildReleaseDecisionReview, releaseDecisionReviewChecksum, validateReleaseDecisionReview, verifyReleaseDecisionReview, RELEASE_DECISION_RECORD_IDS } from "./release-decision-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-decision-review-")); fs.mkdirSync(path.join(root, "work", "decision"), { recursive: true }); for (const id of RELEASE_DECISION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "decision", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function approval(value, status = "pending_closure_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, closure_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_release_decision" ? CLOSURE_APPROVAL_RECORD_IDS.map((id) => ({ id, reference: `work/approval/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], closure_approval_checksum: "" }; result.closure_approval_checksum = releaseClosureApprovalChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_DECISION_RECORD_IDS.map((id) => [id, { reference: `work/decision/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until closure approval is ready", () => { const value = manifest(); const result = buildReleaseDecisionReview({ root: rootFixture(), manifest: value, closureApproval: approval(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_closure_approval"); });
test("accepts twelve decision records", () => { const root = rootFixture(); const value = manifest(); const review = approval(value, "ready_for_release_decision"); const result = buildReleaseDecisionReview({ root, manifest: value, closureApproval: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_release_authorization"); assert.equal(validateReleaseDecisionReview(result, { manifest: value, closureApproval: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.decision_review_checksum, releaseDecisionReviewChecksum(result)); assert.equal(verifyReleaseDecisionReview({ root, document: result }).ok, true); });
test("detects a changed decision record", () => { const root = rootFixture(); const value = manifest(); const review = approval(value, "ready_for_release_decision"); const result = buildReleaseDecisionReview({ root, manifest: value, closureApproval: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "decision", "change_record.md"), "changed\n"); assert.equal(verifyReleaseDecisionReview({ root, document: result }).ok, false); });
test("rejects a fabricated authorization state", () => { const value = manifest(); const review = approval(value); const result = buildReleaseDecisionReview({ root: rootFixture(), manifest: value, closureApproval: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_release_authorization"; assert.equal(validateReleaseDecisionReview(result, { manifest: value, closureApproval: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
