import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseFinalizationChecksum } from "./release-finalization.mjs";
import { releaseLaunchReviewChecksum } from "./release-launch-review.mjs";
import { buildReleaseExecutionReview, releaseExecutionReviewChecksum, validateReleaseExecutionReview, verifyReleaseExecutionReview } from "./release-execution-review.mjs";

const COMMIT = "0123456789abcdef0123456789abcdef01234567";
const RECEIPT = "sha256:" + "c".repeat(64);
const LAUNCH = "sha256:" + "e".repeat(64);
const RECORD_IDS = ["command_authority", "approval_ledger", "dry_run", "execution_log", "release_window", "freeze_clearance", "customer_communication", "rollback_command", "first_hour_watch", "incident_route", "customer_impact_watch", "support_handoff"];

function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-execution-review-")); fs.mkdirSync(path.join(root, "work", "execution"), { recursive: true }); for (const id of RECORD_IDS) fs.writeFileSync(path.join(root, "work", "execution", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function closeout(value) { return { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, generated_at: "2026-01-01T01:00:00.000Z", max_receipt_age_minutes: 1440, receipt_ages_minutes: { github: 5, google_drive: 5 }, status: "release_closeout_ready", receipt_checksum: RECEIPT, errors: [] }; }
function review() { return { status: "export_complete", receipt_checksum: RECEIPT }; }
function finalization(value) { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, closeout_checksum: RECEIPT, generated_at: "2026-01-01T01:00:00.000Z", status: "ready_for_finalization", entries: ["decision", "rollback", "monitoring", "support", "customer_communications", "audit_archive"].map((id) => ({ id, reference: `work/execution/${id}.md`, checksum: "sha256:" + "d".repeat(64), bytes: 1 })), errors: [] }; result.finalization_checksum = releaseFinalizationChecksum(result); return result; }
function launch(value, f) { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, finalization_checksum: f.finalization_checksum, generated_at: "2026-01-01T01:00:00.000Z", status: "ready_for_launch_review", entries: ["launch_window", "freeze_clearance", "ship_owner", "operator", "rollback_trigger", "incident_route", "first_hour_watch", "customer_impact_watch", "command_log_archive", "closeout_timestamp"].map((id) => ({ id, reference: `work/execution/${id}.md`, checksum: "sha256:" + "d".repeat(64), bytes: 1 })), errors: [] }; result.launch_review_checksum = releaseLaunchReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RECORD_IDS.map((id) => [id, { reference: `work/execution/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }

test("stays pending until launch review is ready", () => { const value = manifest(); const f = { status: "pending_closeout", finalization_checksum: "sha256:" + "d".repeat(64) }; const l = { status: "pending_finalization", launch_review_checksum: LAUNCH }; const result = buildReleaseExecutionReview({ root: rootFixture(), manifest: value, closeout: closeout(value), review: review(), finalization: f, launchReview: l, now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_launch_review"); });
test("accepts twelve execution-review records", () => { const root = rootFixture(); const value = manifest(); const f = finalization(value); const l = launch(value, f); const result = buildReleaseExecutionReview({ root, manifest: value, closeout: closeout(value), review: review(), finalization: f, launchReview: l, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_execution_review"); assert.equal(validateReleaseExecutionReview(result, { manifest: value, launchReview: l, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.execution_review_checksum, releaseExecutionReviewChecksum(result)); assert.equal(verifyReleaseExecutionReview({ root, document: result }).ok, true); });
test("detects a changed execution record", () => { const root = rootFixture(); const value = manifest(); const f = finalization(value); const l = launch(value, f); const result = buildReleaseExecutionReview({ root, manifest: value, closeout: closeout(value), review: review(), finalization: f, launchReview: l, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "execution", "dry_run.md"), "changed\n"); const verified = verifyReleaseExecutionReview({ root, document: result }); assert.equal(verified.ok, false); assert.match(verified.errors.join("; "), /dry_run checksum/); });
test("rejects a fabricated ready state", () => { const value = manifest(); const f = finalization(value); const l = launch(value, f); const result = buildReleaseExecutionReview({ root: rootFixture(), manifest: value, closeout: closeout(value), review: review(), finalization: f, launchReview: l, records: {}, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_execution_review"; assert.equal(validateReleaseExecutionReview(result, { manifest: value, launchReview: l, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
