import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseExecutionRequestReviewChecksum, RELEASE_EXECUTION_REQUEST_RECORD_IDS } from "./release-execution-request-review.mjs";
import { buildReleaseExecutionReceiptReview, releaseExecutionReceiptReviewChecksum, validateReleaseExecutionReceiptReview, verifyReleaseExecutionReceiptReview, RELEASE_EXECUTION_RECEIPT_RECORD_IDS } from "./release-execution-receipt-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-execution-receipt-")); fs.mkdirSync(path.join(root, "work", "receipt"), { recursive: true }); for (const id of RELEASE_EXECUTION_RECEIPT_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "receipt", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function request(value, status = "pending_authorization_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, authorization_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_execution_request" ? RELEASE_EXECUTION_REQUEST_RECORD_IDS.map((id) => ({ id, reference: `work/request/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], execution_request_review_checksum: "" }; result.execution_request_review_checksum = releaseExecutionRequestReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_EXECUTION_RECEIPT_RECORD_IDS.map((id) => [id, { reference: `work/receipt/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until execution request is ready", () => { const value = manifest(); const result = buildReleaseExecutionReceiptReview({ root: rootFixture(), manifest: value, executionRequestReview: request(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_execution_request"); });
test("accepts twelve execution-receipt records", () => { const root = rootFixture(); const value = manifest(); const review = request(value, "ready_for_execution_request"); const result = buildReleaseExecutionReceiptReview({ root, manifest: value, executionRequestReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_execution_receipt"); assert.equal(validateReleaseExecutionReceiptReview(result, { manifest: value, executionRequestReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.execution_receipt_review_checksum, releaseExecutionReceiptReviewChecksum(result)); assert.equal(verifyReleaseExecutionReceiptReview({ root, document: result }).ok, true); });
test("detects a changed receipt-readiness record", () => { const root = rootFixture(); const value = manifest(); const review = request(value, "ready_for_execution_request"); const result = buildReleaseExecutionReceiptReview({ root, manifest: value, executionRequestReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "receipt", "traffic_observation.md"), "changed\n"); assert.equal(verifyReleaseExecutionReceiptReview({ root, document: result }).ok, false); });
test("rejects a fabricated receipt-readiness state", () => { const value = manifest(); const review = request(value); const result = buildReleaseExecutionReceiptReview({ root: rootFixture(), manifest: value, executionRequestReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_execution_receipt"; assert.equal(validateReleaseExecutionReceiptReview(result, { manifest: value, executionRequestReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
