import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseAuthorizationReviewChecksum, RELEASE_AUTHORIZATION_RECORD_IDS } from "./release-authorization-review.mjs";
import { buildReleaseExecutionRequestReview, releaseExecutionRequestReviewChecksum, validateReleaseExecutionRequestReview, verifyReleaseExecutionRequestReview, RELEASE_EXECUTION_REQUEST_RECORD_IDS } from "./release-execution-request-review.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-execution-request-")); fs.mkdirSync(path.join(root, "work", "request"), { recursive: true }); for (const id of RELEASE_EXECUTION_REQUEST_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "request", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function authorization(value, status = "pending_decision_review") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, decision_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_operator_authorization" ? RELEASE_AUTHORIZATION_RECORD_IDS.map((id) => ({ id, reference: `work/authorization/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], authorization_review_checksum: "" }; result.authorization_review_checksum = releaseAuthorizationReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_EXECUTION_REQUEST_RECORD_IDS.map((id) => [id, { reference: `work/request/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until authorization review is ready", () => { const value = manifest(); const result = buildReleaseExecutionRequestReview({ root: rootFixture(), manifest: value, authorizationReview: authorization(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_authorization_review"); });
test("accepts twelve execution-request records", () => { const root = rootFixture(); const value = manifest(); const review = authorization(value, "ready_for_operator_authorization"); const result = buildReleaseExecutionRequestReview({ root, manifest: value, authorizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_execution_request"); assert.equal(validateReleaseExecutionRequestReview(result, { manifest: value, authorizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.execution_request_review_checksum, releaseExecutionRequestReviewChecksum(result)); assert.equal(verifyReleaseExecutionRequestReview({ root, document: result }).ok, true); });
test("detects a changed execution-request record", () => { const root = rootFixture(); const value = manifest(); const review = authorization(value, "ready_for_operator_authorization"); const result = buildReleaseExecutionRequestReview({ root, manifest: value, authorizationReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "request", "traffic_scope.md"), "changed\n"); assert.equal(verifyReleaseExecutionRequestReview({ root, document: result }).ok, false); });
test("rejects a fabricated execution-request state", () => { const value = manifest(); const review = authorization(value); const result = buildReleaseExecutionRequestReview({ root: rootFixture(), manifest: value, authorizationReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_execution_request"; assert.equal(validateReleaseExecutionRequestReview(result, { manifest: value, authorizationReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
