import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { releaseExportChecksum } from "./release-export.mjs";
import { releaseExecutionIntakeReviewChecksum, RELEASE_EXECUTION_INTAKE_RECORD_IDS } from "./release-execution-intake-review.mjs";
import { buildReleaseReceiptVerification, releaseReceiptVerificationChecksum, validateReleaseReceiptVerification, verifyReleaseReceiptVerification, RELEASE_RECEIPT_VERIFICATION_RECORD_IDS } from "./release-execution-receipt-verification.mjs";
const COMMIT = "0123456789abcdef0123456789abcdef01234567";
function rootFixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "mgt-receipt-verification-")); fs.mkdirSync(path.join(root, "work", "verification"), { recursive: true }); for (const id of RELEASE_RECEIPT_VERIFICATION_RECORD_IDS) fs.writeFileSync(path.join(root, "work", "verification", `${id}.md`), `${id} record\n`); return root; }
function manifest() { const value = { version: "1.0", candidate_commit: COMMIT, branch: "codex/test", generated_at: "2026-01-01T00:00:00.000Z", status: "ready_for_export", destinations: { github: { status: "pending_push", repository: [], branch: "codex/test", commit: COMMIT }, google_drive: { status: "pending_upload" } }, entries: [], errors: [] }; value.bundle_checksum = releaseExportChecksum(value); return value; }
function intake(value, status = "pending_execution_receipt") { const result = { version: "1.0", candidate_commit: COMMIT, bundle_checksum: value.bundle_checksum, execution_receipt_review_checksum: "sha256:" + "d".repeat(64), generated_at: "2026-01-01T01:00:00.000Z", status, entries: status === "ready_for_external_execution_intake" ? RELEASE_EXECUTION_INTAKE_RECORD_IDS.map((id) => ({ id, reference: `work/intake/${id}.md`, checksum: "sha256:" + "f".repeat(64), bytes: 1, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" })) : [], errors: [], execution_intake_review_checksum: "" }; result.execution_intake_review_checksum = releaseExecutionIntakeReviewChecksum(result); return result; }
function records() { return Object.fromEntries(RELEASE_RECEIPT_VERIFICATION_RECORD_IDS.map((id) => [id, { reference: `work/verification/${id}.md`, owner: "owner", reviewed_at: "2026-01-01T01:00:00.000Z", status: "pass" }])); }
test("stays pending until execution intake is ready", () => { const value = manifest(); const result = buildReleaseReceiptVerification({ root: rootFixture(), manifest: value, executionIntakeReview: intake(value), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "pending_external_execution_intake"); });
test("accepts twenty receipt-verification records", () => { const root = rootFixture(); const value = manifest(); const review = intake(value, "ready_for_external_execution_intake"); const result = buildReleaseReceiptVerification({ root, manifest: value, executionIntakeReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); assert.equal(result.status, "ready_for_receipt_verification"); assert.equal(validateReleaseReceiptVerification(result, { manifest: value, executionIntakeReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, true); assert.equal(result.receipt_verification_checksum, releaseReceiptVerificationChecksum(result)); assert.equal(verifyReleaseReceiptVerification({ root, document: result }).ok, true); });
test("detects a changed verification record", () => { const root = rootFixture(); const value = manifest(); const review = intake(value, "ready_for_external_execution_intake"); const result = buildReleaseReceiptVerification({ root, manifest: value, executionIntakeReview: review, records: records(), now: "2026-01-01T02:00:00.000Z" }); fs.appendFileSync(path.join(root, "work", "verification", "traffic_result_check.md"), "changed\n"); assert.equal(verifyReleaseReceiptVerification({ root, document: result }).ok, false); });
test("rejects a fabricated verification state", () => { const value = manifest(); const review = intake(value); const result = buildReleaseReceiptVerification({ root: rootFixture(), manifest: value, executionIntakeReview: review, now: "2026-01-01T02:00:00.000Z" }); result.status = "ready_for_receipt_verification"; assert.equal(validateReleaseReceiptVerification(result, { manifest: value, executionIntakeReview: review, now: Date.parse("2026-01-01T03:00:00.000Z") }).ok, false); });
