'use client';
import React,{useState} from 'react';import Link from 'next/link';import {hub,useHub} from '../../lib/hub';import {AppFrame,LoadState} from '../../components/HubFrames';
export default function Support(){
 const state=useHub('/support'),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!subject.trim()||!message.trim())return;setBusy(true);setError('');setFeedback('');try{await hub('/support',{subject:subject.trim(),message:message.trim()});setSubject('');setMessage('');setFeedback('Saved to your portal requests.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <AppFrame title="Portal Support"><p className="lead">Keep track of help with your portal.</p><div className="notice">For purchases, billing, shipping or returns, contact the vendor shown on your retailer receipt. <Link className="text-link" href="/orders">Retailer purchase help →</Link></div><p>This development preview stores requests locally. External support delivery and response times are not enabled.</p>{feedback&&<p className="notice success" role="status">{feedback}</p>}{error&&<p className="notice error" role="alert">{error}</p>}
 <form className="panel stack support-form" onSubmit={submit}><span className="eyebrow">NEW PORTAL REQUEST</span><h2>How can we help?</h2><label className="field">Subject<input required maxLength={150} disabled={busy} value={subject} placeholder="A short summary of the issue" onChange={e=>setSubject(e.target.value)}/></label><label className="field">Details<textarea required maxLength={4000} disabled={busy} value={message} placeholder="Describe what happened and which portal page you were using." aria-describedby="support-count" onChange={e=>setMessage(e.target.value)}/></label><span className="muted" id="support-count">{message.length} / 4,000 characters</span><button className="button primary" disabled={busy||!subject.trim()||!message.trim()}>{busy?'Saving…':'Save request'}</button></form>
 <section className="support-history" aria-labelledby="requests-heading"><div className="row"><h2 id="requests-heading">Your requests</h2>{!state.loading&&!state.error&&<span className="pill">{state.data?.tickets.length||0} saved</span>}</div><LoadState {...state} retry={state.reload}/>{!state.loading&&!state.error&&<>{state.data?.tickets.map((t:any)=><article className="panel support-ticket" key={t.id}><div className="row"><h3>{t.subject}</h3><span className="pill">{String(t.status).replace(/_/g,' ')}</span></div><p className="support-message">{t.message}</p>{t.replies.length>0?<section className="support-replies" aria-label="Support replies"><h4>Replies</h4>{t.replies.map((r:any,i:number)=><blockquote key={i}>{r.text}</blockquote>)}</section>:<p className="muted">No replies yet.</p>}</article>)}{state.data?.tickets.length===0&&<div className="empty"><h3>No requests yet.</h3><p>Requests you save will appear here, together with any replies.</p></div>}</>}</section></AppFrame>;
}
